name: flutter_base_source
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  flutter_screenutil: ^5.5.3+2
  shared_preferences: ^2.0.15
  get: 4.6.5
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
